I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/branch2.rpy", line 959, in script
    show cherry_normal as cherry_happy at m3
  File "game/branch2.rpy", line 959, in <module>
    show cherry_normal as cherry_happy at m3
NameError: name 'm3' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/branch2.rpy", line 959, in script
    show cherry_normal as cherry_happy at m3
  File "renpy/ast.py", line 1388, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "renpy/ast.py", line 1347, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "renpy/python.py", line 1080, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 1073, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/branch2.rpy", line 959, in <module>
    show cherry_normal as cherry_happy at m3
NameError: name 'm3' is not defined

Windows-10-10.0.19041 AMD64
Ren'Py 7.5.0.22062402
jcafe_vn_projek_besar 1.0
Mon Sep 19 19:17:03 2022
